#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)/.."

echo "› brew bundle"
brew bundle --file=Brewfile

if test -f Brewfile.local
then
    echo "› brew bundle local found"
    brew bundle --file=Brewfile.local
fi

# find the installers and run them iteratively
echo "› run installers"
find . -name install.sh | while read installer
do
  echo "› run ${installer}"
  sh -c "${installer}"
done

# find the local installers and run them interatively
echo "› run local installers"
if [ -d "$ZSH/local" ]
then
  find "$(realpath "$ZSH/local")" -name install.sh | while read installer
  do
    echo "› run ${installer}"
    sh -c "${installer}"
  done
fi
